
from django.urls import path,include
from .views import CreateAlertView
from alerts.views import AlertViewSet
from . import views
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
router.register(r'alerts', views.AlertViewSet, basename='alert')
router.register(r'transcripts', views.TranscriptViewSet,
                basename='transcript')  # ADD THIS LINE

# The urlpatterns will be automatically generated by the router

ui_patterns = [
    path('create/', CreateAlertView.as_view(), name='create-alert'),
    path('', views.dashboard, name='dashboard'),
]
urlpatterns = [
    # All API URLs will be prefixed with /api/
    path('api/', include(router.urls)),
    *ui_patterns,                        # Add the UI URLs
]
