# Generated by Django 5.2.5 on 2025-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='violation_type',
        ),
        migrations.AddField(
            model_name='alert',
            name='violations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
