# Generated by Django 5.2.5 on 2025-08-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_alert_violation_type_alert_violations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='alert',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='violations/'),
        ),
    ]
