# Generated by Django 5.2.5 on 2025-08-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_video_transcipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcipt',
            new_name='Transcript',
        ),
    ]
